# 多分Looprがなかったら書けてない。
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal}] at @s run scoreboard players add @s battery 20
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=1}] at @s run replaceitem entity @s slot.inventory 0 minecraft:air
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=2}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 1
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=3}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 2
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=4}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 3
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=5}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 4
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=6}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 5
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=7}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 6
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=8}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 7
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=9}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 8
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=10}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 9
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=11}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 10
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=12}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 11
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=13}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 12
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=14}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 13
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=15}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 14
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=16}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 15
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=17}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 16
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=18}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 17
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=19}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 18
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=20}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 19
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=21}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 20
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=22}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 21
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=23}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 22
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=24}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 23
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=25}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 24
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=26}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 25
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=27}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 26
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=28}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 27
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=29}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 28
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=30}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 29
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=31}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 30
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=32}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 31
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=33}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 32
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=34}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 33
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=35}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 34
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=36}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 35
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=37}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 36
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=38}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 37
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=39}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 38
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=40}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 39
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=41}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 40
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=42}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 41
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=43}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 42
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=44}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 43
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=45}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 44
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=46}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 45
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=47}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 46
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=48}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 47
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=49}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 48
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=50}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 49
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=51}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 50
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=52}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 51
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=53}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 52
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=54}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 53
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=55}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 54
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=56}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 55
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=57}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 56
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=58}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 57
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=59}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 58
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=60}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 59
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=61}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 60
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=62}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 61
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=63}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 62
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:coal,quantity=64}] at @s run replaceitem entity @s slot.inventory 0 minecraft:coal 63
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks}] at @s run scoreboard players add @s battery 5
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=1}] at @s run replaceitem entity @s slot.inventory 0 minecraft:air
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=2}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 1
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=3}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 2
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=4}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 3
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=5}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 4
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=6}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 5
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=7}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 6
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=8}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 7
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=9}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 8
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=10}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 9
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=11}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 10
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=12}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 11
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=13}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 12
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=14}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 13
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=15}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 14
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=16}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 15
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=17}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 16
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=18}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 17
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=19}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 18
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=20}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 19
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=21}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 20
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=22}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 21
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=23}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 22
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=24}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 23
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=25}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 24
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=26}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 25
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=27}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 26
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=28}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 27
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=29}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 28
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=30}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 29
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=31}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 30
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=32}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 31
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=33}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 32
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=34}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 33
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=35}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 34
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=36}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 35
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=37}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 36
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=38}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 37
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=39}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 38
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=40}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 39
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=41}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 40
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=42}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 41
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=43}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 42
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=44}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 43
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=45}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 44
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=46}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 45
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=47}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 46
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=48}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 47
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=49}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 48
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=50}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 49
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=51}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 50
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=52}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 51
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=53}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 52
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=54}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 53
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=55}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 54
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=56}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 55
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=57}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 56
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=58}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 57
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=59}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 58
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=60}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 59
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=61}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 60
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=62}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 61
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=63}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 62
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:planks,quantity=64}] at @s run replaceitem entity @s slot.inventory 0 minecraft:planks 63
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp}] at @s run scoreboard players add @s battery 2
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=1}] at @s run replaceitem entity @s slot.inventory 0 minecraft:air
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=2}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 1
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=3}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 2
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=4}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 3
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=5}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 4
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=6}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 5
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=7}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 6
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=8}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 7
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=9}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 8
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=10}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 9
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=11}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 10
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=12}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 11
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=13}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 12
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=14}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 13
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=15}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 14
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=16}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 15
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=17}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 16
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=18}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 17
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=19}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 18
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=20}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 19
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=21}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 20
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=22}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 21
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=23}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 22
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=24}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 23
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=25}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 24
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=26}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 25
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=27}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 26
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=28}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 27
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=29}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 28
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=30}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 29
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=31}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 30
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=32}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 31
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=33}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 32
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=34}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 33
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=35}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 34
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=36}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 35
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=37}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 36
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=38}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 37
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=39}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 38
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=40}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 39
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=41}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 40
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=42}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 41
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=43}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 42
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=44}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 43
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=45}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 44
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=46}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 45
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=47}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 46
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=48}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 47
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=49}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 48
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=50}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 49
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=51}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 50
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=52}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 51
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=53}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 52
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=54}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 53
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=55}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 54
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=56}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 55
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=57}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 56
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=58}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 57
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=59}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 58
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=60}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 59
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=61}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 60
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=62}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 61
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=63}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 62
execute as @e[type=syakai:kugu_htdn,hasitem={item=minecraft:dried_kelp,quantity=64}] at @s run replaceitem entity @s slot.inventory 0 minecraft:dried_kelp 63
execute as @e[type=syakai:kugu_htdn,scores={battery=1..}] at @s if entity @a[r=10,scores={battery=..199}] run tag @s add kugu_htdn
execute as @e[tag=kugu_htdn] at @s run scoreboard players remove @s battery 1
execute as @e[tag=kugu_htdn] at @s as @a[r=10,scores={battery=..199}] at @s run scoreboard players add @s battery 1
execute as @e[tag=kugu_htdn] at @s run tag @s remove kugu_htdn